name: Deploy to Firebase

on: 
  push:
    branches:
      - tomon9086/feature/github-actions
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
<<<<<<< HEAD
        node-version: [8.x, 10.x]
=======
        node-version: [8.x, 10.x, 12.x]
>>>>>>> dfbfaae980c682b47c8ec068ed0fc594c8d6e11a

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
<<<<<<< HEAD
        npm install
        npm run build --if-present
=======
        npm ci
        npm run build --if-present
        npm test
>>>>>>> dfbfaae980c682b47c8ec068ed0fc594c8d6e11a
      env:
        CI: true
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
